version: '3.7'
services:
  lunit-api:
    image: lunit/geo.api:latest
    restart: always
    ports:
      - "3000:3000"
  lunit-db:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"